<?xml version="1.0" ?>
<xsl:stylesheet
xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
xmlns:fo="http://www.w3.org/1999/XSL/Format"
xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" 
xmlns:map="http://www.sitemaps.org/schemas/sitemap/0.9" 
version="1.0"
>
<xsl:template match="/" >
	<html xmlns="http://www.w3.org/1999/xhtml">		
			<head><title>Sitemap</title>
			<link rel="type/stylesheet" href="//R/styles/balafon.css.php" />
			<style type="text/css" >body{background-color:#ececec; }</style>
			</head>
			<body>
				Sitemap.xml generated by BALAFON
				
				<div>
				<h1>Links :</h1> 
					
				</div>
				
				<xsl:for-each select="/map:urlset/map:url" xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" >
								<xsl:variable name="loc">
									<xsl:value-of select="map:loc"/>
								</xsl:variable>
								<div xmlns="http://www.w3.org/1999/xhtml">
								lnk	: <a xmlns="http://www.w3.org/1999/xhtml" href="{map:loc}">  <xsl:value-of select="map:loc"/></a> 
								</div>
				</xsl:for-each>
			
			</body>
	</html>
</xsl:template>

</xsl:stylesheet>