<?php

use IGK\IGKEnvironment;
use function igk_resources_gets as __;

 
$is_prod = !igk_server_is_local() && !igk_app()->Configs->error_debug && igk_sys_env_production();
$base_path = $is_prod;
$cl1 = "#ddd";
$w_padding = "20px";
$content .= ("<div style='height:100%;' > ");
    $content .= ("<h1 style=\"background-color: #efefef; padding: {$w_padding} 20px;\">/!\\ ERROR </h1>");
    if($title){
        $content .= ("<h2>".$title."</h2>");
    }
    $class = $is_prod ? "prod" : "dev";
    $content .= ("<div style=\"color: $cl1; padding: 0px 20px; \">");
    $content .= ("<ul class=\"google-Roboto-Condensed $class\" >");
   
    $from = "";
 
    $tx = $Ex->getPrevious();

    while($tx){
        $file = (($file != null) ? $file: $tx->getFile());
        $from .= "<div> From : <span>".get_class($tx)."</span>";
        $from .= "<ul>";
        $from .= ("<li><span>File :</span>". ($base_path ? igk_io_basepath($file) : $file ).":".
        (($line != null) ? $line: $tx->getLine())
        ."</li>");       
        $from .= "</ul>";
        $from ."</div>";
        $tx = $tx->getPrevious();
    } 

    
    if(!$is_prod){
        
        if (!empty($m = $Ex->getMessage())){
            $content .= ("<li><span>Message: </span>".$m."</li>");
        }
        if (($s = $Ex->getCode())>0){
            $content .= ("<li><span>Code: </span>".$s."</li>");
        }
        // | extra information
        $content .= ("<li><span>Exception Type :</span>".get_class($Ex)."</li>");
        $file = (($file != null) ? $file: $Ex->getFile());
        $content .= ("<li><span>File :</span>". ($base_path ? igk_io_basepath($file) : $file )."</li>");
        $content .= ("<li><span>Line :</span> ".(($line != null) ? $line: $Ex->getLine())."</li>");        
        $content .= "</ul>";

        if (!empty($from)){
            $content .= $from;
        }

        $tabs = [
            "Stack traces"=>function(&$content)use($Ex, $traces, $base_path){
                $content .= "<div>";        
                $content .= igk_get_exception_eval($Ex, $traces);     
                $content .= ("</div>");
                $content .= ("<div id=\"tracelist\" class=\"igk-tracelist\" style=\"overflow:hidden\" >");
                $content .= ("<h2 id=\"hd\">Trace :</h2>");
                $content .= ("<div style=\"overflow-x:auto; width:100%;\" >");
                $content .= ("<table style=\"min-width:450px;\" >");
                foreach($traces as  $v){
                    $content .= ("<tr style=\"margin-bottom:4px; background-color:#efefef; line-height:1.4em; text-overflow: ellipsis; overflow:hidden; white-space: nowrap !important;\">");
                    if(isset($v["file"])){
                        $file = $base_path ? igk_io_basepath($v["file"]) : $v["file"];
                        $content .= ("<td style=\"white-space: nowrap !important;\">File :</td><td style=\"color: #349bdd;\"> ".$file. "</td><td>".$v["line"]."</td><td>".igk_getv($v, "function")."</td>");
                    }
                    else{
                        $content .= ("<td style=\"white-space: nowrap !important;\">File :</td><td> &amp;</td><td style=\"color: #349bdd;\">".igk_getv($v, "line", "__INLINE__")."</td><td>".igk_getv($v, "function")."</td>");
                    }
                    $content .= "</tr>";
                }
                $content .= "</table>";
                $content .= "</div>";
                $content .= "</div>";
            },
            "Request"=>function(&$content){
                $content .= "<table class=\"request\">";
                $content .= "<tr>";
                    $content .= "<td>&nbsp;</td>";
                    $content .= "<td><b>Request</b></td>";
                $content .= "</tr>";                

                $content .= "<tr>";
                    $content .= "<td>URL</td>";
                    $content .= "<td>".igk_server()->REQUEST_URI."</td>";
                $content .= "</tr>";  
                $content .= "<tr>";  
                    $content .= "<td>Method</td>";
                    $content .= "<td>".igk_server()->REQUEST_METHOD."</td>";
                $content .= "</tr>";  

                $content .= "</table>";
                $paggig = [
                    "Headers"=>getallheaders(),
                    "Body"=>[],
                    "Files"=>[],
                    "Sessions"=>[],
                    "Cookies"=>[]
                ];
                foreach($paggig as $k=>$v){

                
                $content .= "<hr />";
                $content .= "<table class=\"request\">";
                $content .= "<tr>";
                    $content .= "<td>&nbsp;</td>";
                    $content .= "<td><b>".$k."</b></td>";
                $content .= "</tr>";
                if (empty($v)){
                    $content .= "<tr>";  
                    $content .= "<td>&nbsp;</td><td>...</td>";
                    $content .= "</tr>";  
                }else{
                    foreach($v as $t=>$m){
                        $content .= "<tr>";  
                        $content .= "<td>".$t."</td>";
                        $content .= "<td>".$m."</td>";
                    $content .= "</tr>";  
                    }
                }
                $content .= "</table>";
                }
            },
            // "App"=>function(& $content){

            // },
            // "User"=>function(& $content){

            // },
            "Server"=>function(& $content){
                $content .= "<table>";
                foreach($_SERVER as $k=>$v){
                    $content.= "<tr>";
                    $content.= "<td>".$k;
                    $content.= "</td>";
                    $content.= "<td>";
                    $content.= is_string($v) ? $v :  (is_array($v) ? implode("\n<br />", $v) : "object");
                    $content.= "</td>";
                    $content.= "</tr>";
                }
                $content .= "</table>";
            },
            "Environment" => function(& $content){
                $c = IGKEnvironment::getInstance()->getEnvironments();
                ksort($c);
                $content .= "<table>";
                foreach($c as $k=>$v){
                    $content.= "<tr>";
                    $content.= "<td>".$k;
                    $content.= "</td>";
                    $content.= "<td>";
                    $content.= is_string($v) ? $v : "ARRAY";// implode("\n<br />", $v);
                    $content.= "</td>";
                    $content.= "</tr>";
                }
                $content .= "</table>";
            }
        ];

        igk_hook("ERROR_DEBUG", ["info"=>& $tab]);

        $mc = "<div class=\"tabcontrol\" style=\"overflow:hidden\" >";
        $content .= "<ul class=\"menu\">";
        foreach($tabs as $k=>$v){
            $content .= "<li>";
            $content .= "<a href=\"#\" >". $k ."</a>";
            $content .= "</li>";
            $mc.="<div class=\"tab dispn\">";
            $v($mc);
            $mc.="</div>";
        }  
        $mc.="</div>";      
        $content .= "</ul>";
        
        $content .= $mc;
        // | presentation trace info 
            $content .= "</div>";
        
        $content .= "<div class='uti-action'>";
        if ($c_session = igk_getctrl(IGK_SESSION_CTRL, false)){
            $buri = $c_session::getBaseFullUri();
            if (session_id()){
            $content .= ("<a href=\"".$buri."&f=ClearS\" class=\"igk-btn\" >". __("Clear session") ."</a>");
            }

            $content .= ("<a href=\"".$buri."&f=clearcache\" class=\"igk-btn\" >".__("Clear Cache")."</a>");
        }
        $content .= ("<a href=\"".igk_io_baseuri()."\" class=\"igk-btn\" > Home </a>");
        $content .= "</div>";
        $content .= "</div>";

    }
    else{
        $code = $Ex->getCode(); 
        $content .="<li class='code-view'>".$code."</li>";
        $content .= "</ul>";
    }  
//no script rendergin
$content .= "<noscript>";
$content .= "Please activate javascript";
$content .= "</noscript>";
$content .= "<script type=\"text/javascript\" language=\"javascript\">";
$content .= file_get_contents(IGK_LIB_DIR."/Inc/exceptions/base.js");
$content .= "</script>";
return $content;