<p>Bonjour{{ user_info }},</p>
<p>&nbsp;</p>
<p>Merci de vous &ecirc;tre enregistr&eacute; sur le site {{ domain }} </p>
<p>&nbsp;</p>
<p>A fin de confirmer votre enregistrement, veuillez clicker sur le lien ci-dessous</p>
<p>&nbsp;</p>
<p><a href="{{ registration_link }}">{{ registration_link }}</a></p>
<p>&nbsp;</p>
<p>Cordialement</p>
<p>L&rsquo;&eacute;quipe {{ domain }} - {{ date }}</p>
<p>&nbsp;</p>
<p>&nbsp;</p>