<p>Bonjour {{ login }},</p>
<p></p>
<p>Quelqu'un a demandé un nouveau mot de passe pour le compte {{ domain }} associé à {{ email }}.</p>
<p></p>
<p>Aucune modification n'a encore été apportée à votre compte.</p>
<p></p>
<p>Vous pouvez réinitialiser votre mot de passe en cliquant sur le lien ci-dessous :</p>
<p></p>
<p><a href="{{ reset_pwd_link }}">{{ reset_pwd_link }}</a></p>
<p></p>
<p>Si vous n'avez pas demandé de nouveau mot de passe, veuillez nous en informer immédiatement en répondant à cet e-mail.</p>
<p></p>
<p>Vôtre,</p>
<p>L'équipe &copy; {{ domain }} - {{ date }}</p>