<p>Hi {{ login }},</p>
<p></p>
<p>Somebody requested a new password for the {{ domain }} account associated with {{ email }}.</p>
<p></p>
<p>No changes have been made to your account yet.</p>
<p></p>
<p>You can reset your password by clicking the link below:</p>
<p></p>
<p><a href="{{ reset_pwd_link }}">{{ reset_pwd_link }}</a></p>
<p></p>

<p>If you did not request a new password, please let us know immediately by replying to this email.</p>
<p></p>
<p>Yours,</p>
<p>The &copy; {{ domain }} team</p>