<?php
// @file: img.fr.phtml
// @author: C.A.D. BONDJE DOUE
// @description:
// @copyright: igkdev © 2020
// @license: Microsoft MIT License. For more information read license.txt
// @company: IGKDEV
// @mail: bondje.doue@igkdev.com
// @url: https://www.igkdev.com

?>
<igk:panelbox>
<div>
Utiliser pour charger une image.
</div>

<igk:code>// ajout d'une image à un noeud
$t->addImg("file_location_uri");</igk:code>

</igk:panelbox>
