<?php

use IGK\Resources\R;

use function igk_resources_gets as __; 
 
//services default pages
$t->clearChilds();
$services = $params["services"];
igk_google_addfont($doc,"Roboto", 400);
$t->setClass("google-Roboto");
//header
$dv = $t->div()->setClass("header");
$dv->addHeaderBar("Services");

$bar = $t->addActionBar();

$t->div()->container()->section()
->quaote()->h2()->Content= __("List of services");
//$body
$dv = $t->div()->setClass("content");
$row = $dv->container()->addRow();
if (igk_count($services) <=0){
	$row->addCol()->addColViewBox()->Content = __("No services found");
}
else{

	$row->addCol("igk-col-3-3")->article($ctrl, $ctrl->getParentArticle("services.list.template"), $ctrl->getServices());
}
$t->div()->setClass("footer")->container()->addSingleRowCol()->div()->addIGKCopyRight();