<?php
// @file: help.igkchangemanagerctrl.fr.phtml
// @author: C.A.D. BONDJE DOUE
// @description:
// @copyright: igkdev © 2020
// @license: Microsoft MIT License. For more information read license.txt
// @company: IGKDEV
// @mail: bondje.doue@igkdev.com
// @url: https://www.igkdev.com

?>
Le controlleur de changement permet de modifier l'apparence du site en fonction des états mis à jour cotés serveur. Son activation entrainera l'utilisation intensive des resources clients. L'activation de javascript côté client est requis;
