<?php
// @file: help.IGKCommunityLink.fr.phtml
// @author: C.A.D. BONDJE DOUE
// @description:
// @copyright: igkdev © 2020
// @license: Microsoft MIT License. For more information read license.txt
// @company: IGKDEV
// @mail: bondje.doue@igkdev.com
// @url: https://www.igkdev.com

?>
<h2>Que pouvons nous faire sans la communautaire?</h2>
<p>
Administrer ici vos lien communautaire. vous auvez la possibilité en plus de modifier leur visibilité.
</p>
