<?php
// @file: class.igkhtmlrollowneritem.fr.phtml
// @author: C.A.D. BONDJE DOUE
// @description:
// @copyright: igkdev © 2020
// @license: Microsoft MIT License. For more information read license.txt
// @company: IGKDEV
// @mail: bondje.doue@igkdev.com
// @url: https://www.igkdev.com

?>
<div>
Element composé. Le contenu (Content) est la partie visible et l'élément de survole (Roll) est la partie qui
deviendra visible au passage de la souris sur le contenu.
</div>
