<?php
// @file: class.igkhtmlajxviewitem.fr.phtml
// @author: C.A.D. BONDJE DOUE
// @description:
// @copyright: igkdev © 2020
// @license: Microsoft MIT License. For more information read license.txt
// @company: IGKDEV
// @mail: bondje.doue@igkdev.com
// @url: https://www.igkdev.com

?>
<dd>Element qui permet de charger du contenue de manière asynchrone.</dd>
à la différence de l'iframe le résultat peut être préfilter et une visualisation de chargement sera rendu.
<igk:code>
$t = igk_create_node();
$t->addAJXView()->setUri("//url_to_resources");
</igk:code>
<div class="igk-remark">
    Pour des raisons de sécurité Uri doit appartenir au domaine.
</div>
