<?php
// @file: class.igkhtmltrackbaritem.fr.phtml
// @author: C.A.D. BONDJE DOUE
// @description:
// @copyright: igkdev © 2020
// @license: Microsoft MIT License. For more information read license.txt
// @company: IGKDEV
// @mail: bondje.doue@igkdev.com
// @url: https://www.igkdev.com

?>
<div>
<div class="floatl" style="width:100px" >Trackbar</div>
<div class="floatl" style="min-width:400px; padding-bottom:10px;"> Barre de traction.
Le composant requiert l'attribute <code>igk-trb-data</code> pour passer ses paramètres.
<p>
Exemple:
<p>
<code class="no-wrap">
$track->setAttribute("igk-trb-data", "{update: function(d){ if (!d.bar.rep) d.bar.rep = d.bar.target.add('div'); d.bar.rep.setHtml(d.progress); }}");
</code>
</p>

</p>
</div>
<igk:clearTab />
</div>
