<?php
// @file: class.igkhtmlauthorizationnodeitem.fr.phtml
// @author: C.A.D. BONDJE DOUE
// @description:
// @copyright: igkdev © 2020
// @license: Microsoft MIT License. For more information read license.txt
// @company: IGKDEV
// @mail: bondje.doue@igkdev.com
// @url: https://www.igkdev.com

?>
<div>
Element d'autorisation. il s'agit d'un noeud qui se rendra visible seulement si l'internaute possède les autorisations nécessaires.
</div>

<div>
<igk:panel>Exemple</igk:panel>
<code>
$t->addAuthorizationNode("system/adduser");
</code>
</div>
