<?php
// @file: default.phtml
// @author: C.A.D. BONDJE DOUE
// @description:
// @copyright: igkdev © 2020
// @license: Microsoft MIT License. For more information read license.txt
// @company: IGKDEV
// @mail: c.bondje.doue@igkdev.com
// @url: https://www.igkdev.com

/**
 * @var mixed $t
 */

use IGK\api\ApiVersion;

///<summary>Represente class: IGKAPIInfo</summary>
/**
* Represent IGKAPIInfo class
*/
require_once IGK_LIB_DIR.'/api/Lib/Classes/ApiVersion.php';
 
igk_google_addfont($doc, "Roboto");
$doc->Title="Api - [".IGK_PLATEFORM_NAME."]";
$t->clearChilds();
$t["class"]="google-Roboto";
$dv=$t->div();
$dv["style"]="padding:2em";
$dv->addSectionTitle(5)->Content="BALAFON <span>Api version <span>".ApiVersion::VERSION."</span></span>";
$c=$t->div();
$c=$c->container();
if(igk_is_conf_connected()){
    $col=$c->addSingleRowCol();
    $dv=$col->div();
}
$dv=$t->div()->setStyle("padding-left:2em");
$ul=$dv->add("ul");
foreach(["datadb"] as $k){
    $ul->add("li")->addA($ctrl->getAppUri($k))->Content=$k;
}
$t->div()->setStyle("padding-left:2em")->addIGKCopyright();