<?php
// @file: default.homepage.nl.phtml
// @author: C.A.D. BONDJE DOUE
// @description:
// @copyright: igkdev © 2020
// @license: Microsoft MIT License. For more information read license.txt
// @company: IGKDEV
// @mail: bondje.doue@igkdev.com
// @url: https://www.igkdev.com

?>
<div class="igk-container">
<div class="igk-row">
<div class="igk-col">
<div>
<div style="margin-bottom: 4em" ></div>
<h2>Welkom bij BALAFON framework</h2>
	<div class="fm-title">BALAFON
<?php
echo IGK_VERSION;
?></div>
</div>
</div>
</div>
</div>
<?php
$c=igk_create_node("container");
$c->addRow()->addCol("igk-col-3-3 igk-col-xsm-3-3  igk-col-sm-3-3")->addDiv()->addObData(function(){
	$buri = igk_io_baseuri();
    ?>
<div style="line-height:2.8em">
	<p>We thank you. By using Balafon. </p>
	<p class="igk-danger igk-panel" style="line-height:1.4;">
		hoofd <b>controller</b> van uw website
	</p>

<div class="mfo" >
Voor meer informatie ... <a href="//igkdev.com/balafon/wiki"> lees de documentatie. </a>
</div>
<div class="mfo">
	<a href="<?= $buri ?>/Configs">Configs</a>
</div>

</div>
<?php
});
$c->renderAJX();
