<?php
// @file: default.homepage.fr.phtml
// @author: C.A.D. BONDJE DOUE
// @description:
// @copyright: igkdev © 2020
// @license: Microsoft MIT License. For more information read license.txt
// @company: IGKDEV
// @mail: bondje.doue@igkdev.com
// @url: https://www.igkdev.com
// @requireby: HtmlDefaultMainPage.php


?>
<div class="igk-container">
<div class="igk-row">
<div class="igk-col">
<div>
<div style="margin-bottom: 4em" ></div>
<h1>BALAFON web plateform</h1>
	<div class="fm-title">BALAFON <?= IGK_VERSION; ?></div>
</div>
</div>
</div>
</div>
<?php
$c=igk_create_node("container");
$c->addRow()->addCol("igk-col-3-3 igk-col-xsm-3-3  igk-col-sm-3-3")->div()->addObData(function(){
	$buri = igk_io_baseuri();
    ?>
<div style="line-height:2.8em">
	<p >Merci d'avoir choisi BALAFON comme plateforme de développement web.</p>
	<p class="igk-danger igk-panel" style="line-height:1.8em; font-size: 0.8em; font-weight: 100;">
		Oups!!! Le system ne détecte pas de contrôleur principal.
	</p>
	<div class="mfo" style="margin-top:20px" >
		<a class="igk-btn no-border" href="//igkdev.com/balafon/wiki"><b>Documentation</b></a>
		<?php
		if (!igk_environment()->noWebConfiguration()):
		?>
			<a class="igk-btn no-border" href="<?= $buri ?>/Configs" class="">Configuration</a>
		<?php
		endif;
		?>
	</div>
</div>
<?php
});
$c->renderAJX();
