<?php

// @author: C.A.D. BONDJE DOUE
// @filename: config.default_page.phtml
// @date: 20220425 11:22:28
// @desc: default configuration page

// Server::RemoteIp();
// :domain info
//TODO: CACHE TOOL

use IGK\Helper\JSon;
use IGK\Resources\R;
use IGK\Server;
use IGK\System\IO\InlineScriptLoader;
use IGK\System\IO\Path;

use function igk_resources_gets as __;

igk_require_module('igk\\ovh', null, 0, 0);

// igk_wln_e( \IGK\System\Modules\ModuleManager::GetRequiredModules());
$ctrl->setSelectedConfigCtrl(null);

$box = igk_html_ctrl_view_config($ctrl, $cnf_n, "title.frameworkInfo", null);
$box->setClass("home-cnf");
$ctrl->_selectMenu("home", "IGKConfigCtrl::setpage");
$ul = $box->addPanelBox()->add("ul")->setClass("gen_inf");


$ul->li()->Content = "FrameworkCodeName : " . IGK_PLATEFORM_NAME;
$ul->li()->Content = "FrameworkVersion : " . IGK_VERSION;
$ul->li()->Content = "FrameworkRelease : " . IGK_RELEASE_DATE;
$ul->li()->Content = "Author : " . IGK_AUTHOR;
$li = $ul->add("li", array("class" => "alignt"));
$li->add("span", array("class" => "alignt -lblabel"))->Content = "Author Contact : ";
$li->add("a", array(
    "class" => "alignt deco_u",
    "style" => "text-decoration:underline",
    "href" => "mailto:" . IGK_AUTHOR_CONTACT
))->Content = "@igkdev.com";
$ul->li()->Content = "PhpVersion : " . PHP_VERSION;
if (function_exists("apache_get_version"))
    $ul->li()->Content = "Apache Version : " . apache_get_version();
$ul->li()->Content = "ServerName : " . igk_server_name();
$ul->li()->Content = "OS : " . PHP_OS;
$ul->li()->Content = "OS Details: " . php_uname();
$ul->li()->Content = "UserAgent : " . IGKUserAgent::Agent();
$ul->li()->Content = "ServerIP: " . Server::ServerAddress();
$ul->li()->Content = "RemoteIP : " . Server::RemoteIp();
$ul->li()->Content = "IsLocal : " . igk_parsebool(Server::IsLocal());
$ul->li()->Content = "BaseDir : " . igk_io_basedir();
$ul->li()->Content = "LibDir : " . IGK_LIB_DIR;
$ul->li()->Content = "Environment: " . igk_environment()->name();
if ($sess_id = session_id()) {
    $ul->li()->Content = "Session ID: " . $sess_id;
}
$ul->li()->Content = "GIT: " . "<a href=\"" . IGK_GIT_URL . "\" target=\"__blank\" > " . IGK_GIT_URL . " </a>";

$frm = $box->addForm();
$frm["action"] = $ctrl->getUri("conf_install_platform");
$frm["class"] = "dispn";
$frm["enctype"] = "multipart/form-data";
$i = $frm->addInput("clFile", "file");
$i["accept"] = ".zip";
$lang = json_encode([
    "wait" => __("please wait... installing"),
    "complete" => __("install complete !!!"),
]);
$i["onchange"] = "javascript: ns_igk.os.install(this.form, {$lang}); return false;";
$i["class"] = "igk-btn igk-btn-default alignl dispib";

$domain = igk_lib_configs()->get("website_domain");

if (igk_environment()->isDev() || ($domain == igk_server()->SERVER_NAME) || ($domain == "*")) {



    // + | ---------------------------------------------------------------------------
    // + | check for update - once only on fist 
    // + | 
    if ((strpos(igk_server()->HTTP_HOST, 'igkdev.') !== false) && !igk_app()->session->checkVersion) {
        $frm = $box->addForm();
        $frm->addLineWaiter();
        $u = "https://igkdev.com/balafon/check-update/" . IGK_VERSION . "/" . R::GetCurrentLang();
        $frm->addBalafonJS()->Content = "igk.os.checkupdate('{$u}');";
        igk_app()->session->checkVersion = 1;
    }

    $uform = $box->addPanelBox()->div();
    if (igk_io_basedir_is_root() && function_exists("zip_open")) {
        $cl = \IGK\System\Installers\BalafonInstaller::class;
        $_ag = $uform->actiongroup()->setClass("update-group-flex-alignc");
        if (class_exists($cl)) {
            $uri = igk_register_temp_uri($cl);

            $_ag->div()->setClass("igk-btn no-padding igk-btn-core-update")
                ->addAJXPickFile($uri . "/upload", "{complete:igk.core.install('" . $uri . "/update" . "', '#update_target')," . "progress:igk.core.progress('#update_target')," . "accept:'.zip'" . "}")
                ->setAttribute("value", __("Update CoreLib"));
            $uform->div()->setId("update_target");
            $uform->script()->Content =  file_get_contents(dirname(__FILE__) . '/Scripts/configs/installer.js');
        }
        // + | ovh service for firewal management
        /**
         * @var object $srv
         */
        if ($srv = igk_app()->getService("ovh")) {
            if ($srv->supportConfig()) {
                $rd = $_ag->div()->setClass("igk-btn");
                if ($srv->enable_firewall) {
                    $rd->a($srv->disable_firewall_uri())->Content = __("Disable Ovh firewall");
                } else {
                    $rd->a($srv->enable_firewall_uri())->Content = __("Enable ovh firewall");
                }
            }
        }
        igk_hook("filter_config_actionbar", ["host" => $_ag]);
        //support
        igk_hook("filter_config_default_bar", ["host" => $uform]);
    }
}

$div = $box->addPanelBox()->div();
igk_html_add_title($div, __("Administration"));
$div->addHSep();
$frm = $div->addForm()->setClass("fitw");
$frm["action"] = $ctrl->getUri("update_domain_setting");
igk_notify_sethost($frm, "update_domain_setting");
$frm->div()->addSLabelInput("company_name", "text", $app->Configs->company_name);
$frm->div()->addSLabelInput("website_domain", "text", $app->Configs->website_domain, null, true);
$frm->div()->addSLabelInput("website_title", "text", $app->Configs->website_title);
$frm->div()->addSLabelInput("website_prefix", "text", $app->Configs->website_prefix);
$frm->div()->addSLabelInput("website_adminmail", "email", $app->Configs->website_adminmail);

$dv = $frm->div();
$dv->addBtn("btn_domainName", __("Update"));
igk_hook("sys//config/general_setting", [$this, "node" => $box]);
$frm = $box->addPanelBox()->addForm();
$frm->input("username", "text")->setStyle("display:none");
$frm->setId("adminpwd-form");
$frm["action"] = $ctrl->getUri("update_adminpwd");
igk_notify_sethost($frm->div(), "update_adminpwd");
$frm->addSLabelInput("passadmin", "password", null, ["autocomplete" => "new-password"]);
$frm->addBr();
$frm->addBtn("btn.updateadminpwd", __("Update"));

// renew

if (igk_configs()->webauthn || igk_configs()->webauthn_required || igk_configs()->webauthn_serie_key) {
    $js_loader = new InlineScriptLoader(IGK_LIB_DIR . '/Scripts/.inc/configs/web-authentication.js');

$tbox = $box->addPanelBox()->setClass('wa-credentials')->setStyle('display:none');
if (igk_configs()->webauth_serie_key) {
    $tbox->addBtn("btn.updateadminpwd", __("Renew WebAuthentication"))->setClass('renew-webauth-btn');
} else {
    $tbox->addBtn("btn.updateadminpwd", __("Create WebAuthentication"))->setClass('renew-webauth-btn');
}
$tbox->script()->content = $js_loader->content();
$v_confctrl = igk_getconfigwebpagectrl();
$uri = igk_uri(Path::CombineAndFlattenPath( igk_io_baseuri(),  $v_confctrl->getUri('webauthn-create-register')));
$v_toggle_uri = igk_uri(Path::CombineAndFlattenPath( igk_io_baseuri(),  $v_confctrl->getUri('toggle-webauth-requirement')));

$tbox->checkbox('cbox_webauth_requirement')->on('click', 'igk.ajx.post("'.$v_toggle_uri.'")')
->setAttribute('value', igk_configs()->webauth_serie_key)
->setContent('Toggle WebAuthRequirement');
// igk_wln_e(__FILE__.":".__LINE__ , "the uri ", $uri);
$tbox->script()->content = <<<JS
(function(){
    const p = \$igk('.wa-credentials').first(); 
    igk.ready(function(){
    if (navigator.credentials){
        p.setCss({display:null});
    }else{return;}
\$igk('.renew-webauth-btn').each_all(function(){
    this.on('click', async ()=>{
        await igk.auth.webAuthn.register("{$uri}")
    });
});
});
})();
JS;

}


$frm = $box->addPanelBox()->addForm();
$frm["action"] = $ctrl->getUri("update_defaultlang");
$frm->addHSep();
if (!$app->Configs->default_lang) {
    $app->Configs->default_lang = R::GetCurrentLang();
}
$tab = R::GetSupportedLangs();
$tab = array_merge($tab);
$dv = $frm->div();
$dv->addLabel("cldefaultLang")->Content = R::ngets("lb.cldefaultlang");
$select = igk_html_build_select($dv, "cldefaultLang", $tab, array("allowEmpty" => false, "keysupport" => false), $app->Configs->default_lang);
$select["class"] = "igk-form-control cltext";
$frm->addBr();
$frm->addBtn("btn.updateCurrentLang", __("Update"));
$frm = $box->addPanelBox()->addForm();
$frm["action"] = $ctrl->getUri("update_default_tagname");
$frm->addHSep();
$frm->addSLabelInput("cldefault_node_tagname", "text", $app->Configs->app_default_controller_tag_name);
$frm->addBr();
$frm->addBtn("btn.updateGlobalSetting", __("Update"));
$frm = $box->addPanelBox()->addForm();
$frm["action"] = $ctrl->getUri("conf_update_setting");
$div = $frm->div();
$ul = $div->add("ul");
$ul["class"] = "igk-row other-conf-setting";
$tab = [
    "cldebugmode" => ["t" => "allow_debugging", "v" => igk_configs()->allow_debugging],
    //"clallowlog"=>["t"=>"allow_log", "v"=>false],
    // "clCacheLoadedFile" => ["t" => "cache_loaded_file", "v" => igk_configs()->cache_loaded_file],
    "clarticleconfig" => ["t" => "allow_article_config", "v" => igk_configs()->allow_article_config],
    "clinformAccessConnection" => ["t" => "informAccessConnection", "v" => igk_configs()->informAccessConnection],
    // "clautocachepage" => ["t" => "allow_auto_cache_page", "v" => igk_configs()->allow_auto_cache_page]
];
foreach ($tab as $s => $kt) {
    $div = $ul->li()->setClass("igk-col fitw")->div();
    $t = $kt["t"];
    $v = $kt["v"];
    $div->addLabel()->setAttribute("for", $s)->Content = __("lb." . $t);
    $div->addToggleStateButton($s, "on", $v)->setClass("dispib"); //->setAttribute("onchange", "ns_igk.ajx.get('{$u}&cache='+ns_igk.geti(event.target.checked),null,ns_igk.ajx.fn.no); return false;");

}
// $li = $ul->li()->setClass("igk-col fitw igk-col-lg-3-1")->div();
// $li->addLabel()->Content = R::ngets("lb.clcache_file_time");
// $li->addInput("clcache_file_time", "text", igk_getdv($app->Configs->cache_file_time, 3600))->setAttribute("style", "width:80px");
$dv = $frm->div()->setStyle("margin-top:2em");
$dv->addBtn("btn_updatedebugmode", __("Update"));


$ctrl->__init_cache_tools($box->addPanelBox()->div());
$ctrl->__init_log_tools($box->addPanelBox()->div());

$fx = $box->addPanelBox();
$frm = $fx->addForm();
$frm["action"] = $ctrl->getUri("resetconfig");
$frm["class"] = "dispib btn-form";
$frm->getBox()->actiongroup()->addBtn("btn_resetconfig", R::ngets("btn.resetconfig"));
$frm = $fx->addForm();
$frm["action"] = $ctrl->getUri("conf_runCtrlConfig");
$frm["class"] = "dispib btn-form";
$frm->getBox()->actiongroup()->addBtn("btn_runctrlconfig", R::ngets("btn.runctrlSetupConfig"));
$dv = $fx->div()->setClass("btn-form igk-action-group");
$v_conf_path = igk_server()->getConfigurationSettingPath();
$dv->addABtn(igk_io_baseuri() . $v_conf_path)->setclass("clsubmit igk-btn-default dispib")->Content = __("General Configuration");
if (Server::IsLocal() || igk_is_conf_connected() || !igk_sys_env_production()) {
    $dv->add('a')->setClass("clsubmit igk-btn igk-btn-default dispib")->setAttribute("href", $ctrl->getUri("clearcache"))
        //->setAttribute("onclick", "javascript: ns_igk.ajx.get(this.href+'&ajx=1', null,{src:this,complete:function(xhr){ ns_igk.ajx.fn.prepend_to(xhr,this.src.parentNode); }});  return false;")
        ->Content = __("Clear cache");

    $dv->abtn($ctrl->getUri("runcron"))->setClass("clsubmit igk-btn-default")->Content = __("Run Cron");
}

$fx->div()->toast_notify("run:cron");
