<?php 
// @author: C.A.D. BONDJE DOUE
// @filename: general.config.view.phtml
// @date: 20220425 11:21:11
// @desc: default configuration view node

use function igk_resources_gets as __;

/**
 * @var HtmlNode $t node
 * @var IGKHtmlDoc $doc document
 */

$doc->Title=__("Global configurations");
$doc->getTheme()->addTempFile($ctrl->getStylesDir()."/conf.setting.pcss");
if(file_exists($ftfile=IGK_LIB_DIR."/Default/R/Fonts/global.ttf")){
    $doc->Theme->addFont("global", $ftfile);
}
unset($ftfile);
igk_google_addfont($doc, "Roboto");
$t->clearChilds();
$t["class"]="google-Roboto";
$doc->head->addCssStyle("base", 0)->setAttribute("type", "text/css")->Content=<<<EOF
@bg_color:transparent;
body.igk-body{
background-color:@bg_color;
}
EOF;

$bbox=$t->div();
$bbox->setClass("overflow-y-a fith");
$hd=$bbox->div()->setClass("header");
if(!($ref=$ctrl->getParam("referer"))){
    $ref=igk_sys_srv_referer() ?? igk_io_baseuri();
    $ctrl->setParam("referer", $ref);
}
$hd->addA($ctrl->getUri("back"))->addFontSymbol("global", 0xF001);
$hd->addSectionTitle(4)->Content= __("Configurations");
$h=$bbox->div();
$f=$h->addForm();
$f["style"]="padding:4px;";
$f["action"]=$ctrl->getUri("configure_search_ajx");
$f["onsubmit"]="return false;";
$r=$f->div();
$r->addLabel("Find")->setClass("dispib floatl");
$r->addInput("clsearch", "text")->setClass("dispi floatl")->setAttribute("onkeyup", "javascript: ns_igk.ajx.fn.postData(this.form.action, this, '#vr'); return ;");
$r->addClearTab();
$r->addInput("btn.search", "submit")->setClass("dispn");
$h=$bbox->div()->setId("vr")->setClass("overflow-y-a loc_l loc_b loc_r");
$h->google_line_waiter();
$h->addAJXUriLoader($ctrl->getUri("configure_search_ajx"));