<?php 

/**
 * @var HtmlNode$t node
 */
use function igk_resources_gets as __;


$doc->Title=__("Global configurations");
$doc->Theme->addTempFile($ctrl->getStylesDir()."/conf.setting.pcss");
if(file_exists($ftfile=IGK_LIB_DIR."/Default/R/Fonts/global.ttf")){
    $doc->Theme->addFont("global", $ftfile);
}
unset($ftfile);
igk_google_addfont($doc, "Roboto");
$t->clearChilds();
$t["class"]="google-Roboto";
$doc->head->addCssStyle("base", 0)->setAttribute("type", "text/css")->Content=<<<EOF
@bg_color:transparent;
body.igk-body{
background-color:@bg_color;
}
EOF;

$bbox=$t->div();
$bbox->setClass("overflow-y-a fith");
$hd=$bbox->addDiv()->setClass("header");
if(!($ref=$ctrl->getParam("referer"))){
    $ref=igk_sys_srv_referer() ?? igk_io_baseuri();
    $ctrl->setParam("referer", $ref);
}
$hd->addA($ctrl->getUri("back"))->addFontSymbol("global", 0xF001);
$hd->addSectionTitle(4)->Content= __("Configurations");
$h=$bbox->addDiv();
$f=$h->addForm();
$f["style"]="padding:4px;";
$f["action"]=$ctrl->getUri("configure_search_ajx");
$f["onsubmit"]="return false;";
$r=$f->addDiv();
$r->addLabel("Find")->setClass("dispib floatl");
$r->addInput("clsearch", "text")->setClass("dispi floatl")->setAttribute("onkeyup", "javascript: ns_igk.ajx.fn.postData(this.form.action, this, '#vr'); return ;");
$r->addClearTab();
$r->addInput("btn.search", "submit")->setClass("dispn");
$h=$bbox->addDiv()->setId("vr")->setClass("overflow-y-a loc_l loc_b loc_r");
$h->addAJXUriLoader($ctrl->getUri("configure_search_ajx"));