<?php
// @file: installsite.phtml
// @author: C.A.D. BONDJE DOUE
// @description:
// @copyright: igkdev © 2020
// @license: Microsoft MIT License. For more information read license.txt
// @company: IGKDEV
// @mail: bondje.doue@igkdev.com
// @url: https://www.igkdev.com

use IGK\System\Installers\InstallerUtils;

use function igk_resources_gets as __;
if(isset($source_args)){
    extract($source_args);
}
igk_view_handle_actions($fname, ["install"=>function(){
            if(!igk_valid_cref(1)){
                return;}
            $LIB=igk_uri(IGK_LIB_DIR."/igk_framework.php");
            ($home=igk_getv($_SERVER, "HOME")) || ($home=igk_getv($_SERVER, "DOCUMENT_ROOT"));
            $home=trim(igk_str_rm_last(igk_uri($home), "/"));
            $site_dir=trim(ltrim(igk_uri(igk_sys_getconfig("site_dir")), "/"));
            $dir=ltrim(igk_uri(trim(igk_getr("diri"))), "/");
            $dir_home=igk_str_rm_last($home."/".$site_dir, '/');
            $install=$dir_home."/".$dir;
            if(!empty($dir)){
                $module=igk_getr("use_comnon_mod");
                $sitename=basename($install);
                igk_io_createdir($install."/src/public");
                igk_io_createdir($install."/src/application");
                igk_io_createdir($install."/src/tmp");
                $module_path="{$install}/application/".IGK_PACKAGES_FOLDER."/Modules";
                if($module){
                    $module_path=igk_uri(igk_get_module_dir());
                }
             
                $source = InstallerUtils::GetEntryPointSource([
                    "app_dir"=>$install."/application",
                    "project_dir"=>$install."/application/Projects",
                    "entry_app_dir"=>"../",
                ]);  
                igk_io_w2file("{$install}/src/public/index.php", $source);
                igk_notifyctrl("site_install")->addSuccess(__("Site install done : {0}", $install));
            }
        }
], $params);
$t->clearChilds();
$t->addNotifyHost("site_install");
$frm=$t->addForm();
$frm["action"]=$ctrl->getAppUri($fname."/install");
$frm->add("h3")->Content=__("Install Site utility");
$formfields=["diri"=>["type"=>"text",
            "label_text"=>__("Site"),
            "value"=>"/",
            "attrs"=>[]
        ],
        "use_comnon_mod"=>["type"=>"checkbox",
            "label_text"=>__("Use Common modules"),
            "value"=>1
        ]
    ];
$frm->addFormFields($formfields);
$frm->addActionBar()->addInput("btn.submit", "submit");
igk_html_form_initfield($frm);