<?php
// @file: subdomain.config.phtml
// @author: C.A.D. BONDJE DOUE
// @description:
// @copyright: igkdev © 2020
// @license: Microsoft MIT License. For more information read license.txt
// @company: IGKDEV
// @mail: bondje.doue@igkdev.com
// @url: https://www.igkdev.com

use function igk_resources_gets as __;
use IGK\Resources\R;
use IGK\System\Html\HtmlUtils; 
$t->clearChilds();
$t->div()->setStyle("display:none")->Content="Subdomain Manager";
$t->div()->addTitleLevel(4)->Content= __("Sub-Domain");
$t->addHSep();
$dom=IGKSubDomainManager::GetBaseDomain();
$dv=$t->div();
$dv["class"]="igk-roll-owner";
$dv->Content=$dom;
$dv->addRollIn()->setClass("igk-pull-right")->addAJXA($ctrl->getUri("dom_add_db_edit_domain_ajx"))->addResImg("edit_16x16");
 

$vlist=IGKSubDomainManager::getInstance()->domainList();
if($vlist && (count($vlist) > 0) ){
    $tdv=$t->div();
    $tdv["class"]="igk-row";
    $tdv["style"]="margin:0px; margin-bottom:10px;";
    $tdv->div()->addTitleLevel(5)->Content=R::ngets("title.SystemDomain");
    $dv=$tdv->div();
    foreach($vlist as $k=>$v){
        $dv->add("div")->setClass("floatl")->setStyle("width:180px;")->Content=$v;
    }
}

$t->div()->host([$this, "subdomain_view"]);
 

$b=$t->div()->form()->setClass("subdomain-action")->actionbar()->setClass("no-margin");
$b->addAJXA($ctrl->getUri("dom_add_db_domain_ajx"))->setClass("igk-btn")->addResImg("add_16x16");
$a=$b->addA($ctrl->getUri("dom_drop_db_s_domain_ajx"))->setClass("igk-btn");
$a["onclick"]="javascript: var s = \$igk(this).select(\"^.c-z\").getItemAt(0).select(\"form\").getItemAt(0);"."ns_igk.ajx.postform(s.o, this.href, ns_igk.ajx.fn.replace_or_append_to_body); return false;";
$a->addResImg("drop_16x16");
$b->addAJXA($ctrl->getUri('dom_drop_domaintable'))->setClass("igk-btn")->div() //->setStyle("line-height:1")
->setContent(__("Clear Table"));
$t->addBalafonJS()->Content=<<<EOF
igk.system.createNS('igk.conf.subdomain', {
	drop: function(t){
		if (window.confirm(ns_igk.R.format('Please Confirm {0}', t.getAttribute('domain')))){
			igk.ajx.post(t.href, ["confirm=1"], function(xhr){
				if (this.isReady()){
					console.debug("droped");
				}
			});
		}
	}
});
EOF;

