<?php
// @file: subdomain.editbasedomain.form.phtml
// @author: C.A.D. BONDJE DOUE
// @description:
// @copyright: igkdev © 2020
// @license: Microsoft MIT License. For more information read license.txt
// @company: IGKDEV
// @mail: bondje.doue@igkdev.com
// @url: https://www.igkdev.com

$d=$t->addDiv();
$d->addInput("clName", "text", IGKSubDomainManager::GetBaseDomain());
$t->addDiv()->addSubmitBtn("btn_edit", "btn.edit");