<?php
// @file: subdomain.edit.form.phtml
// @desc: edit domain form
// @author: C.A.D. BONDJE DOUE
// @update:24/01/2018

include_once(dirname(IGK\Helper\ViewHelper::File())."/subdomain.fc.pinc");
$tab=igk_get_all_uri_page_ctrl();
igk_notifyctrl()->setNotifyHost($t->div());
$dv=$t->div();
igk_assert_die($params == null || !($data=igk_getv($params, "data")), "parameter is null or empty");
$dv->addInput("clId", "hidden", $data->clId);
igk_subdomain_fc_inflate($tab, $t, $data, 2); 