<?php
// @file: subdomain.add.form.phtml
// @author: C.A.D. BONDJE DOUE
// @description:
// @copyright: igkdev © 2020
// @license: Microsoft MIT License. For more information read license.txt
// @company: IGKDEV
// @mail: bondje.doue@igkdev.com
// @url: https://www.igkdev.com

include_once(IGK_LIB_DIR."/Views/subdomain.fc.pinc");
$t->clearChilds();

$tab=igk_get_all_uri_page_ctrl();
igk_subdomain_fc_inflate($tab, $t);

// $t->addOnRenderCallback(function(){
//     igk_wl("<div>rendering ... </div>", igk_get_all_uri_page_ctrl());
// });