<?php
// @file: tab.views.phtml
// @author: C.A.D. BONDJE DOUE
// @description:
// @copyright: igkdev © 2020
// @license: Microsoft MIT License. For more information read license.txt
// @company: IGKDEV
// @mail: bondje.doue@igkdev.com
// @url: https://www.igkdev.com
/** @var BaseController $s_ctrl */

use function igk_resources_gets as __; 
use IGK\Resources\R;
use IGK\Helper\IGKControllerHelper;
use IGK\System\Html\Dom\HtmlSearchNode;
use IGK\System\Html\HtmlUtils;

($s_ctrl == null) && igk_die("selected controller not found");
    $div=$t;
if (!igk_is_ajx_demand())
$div->add("h3")->Content = __("Views for {0}", $s_ctrl->getName());
$div->add(new HtmlSearchNode($ctrl->getUri("search_view#frm_ctrl_view"), null, "m_search_view"));
$frm=$div->addForm();
$frm->setId("frm_ctrl_view");
$frm["action"]=$ctrl->getUri("ca_add_view_frame");
$frm["igk-ajx-form"]=1;
$t=array();
$ln=0;
if(method_exists($ctrl, "ListViewFile")){
    $t=$s_ctrl->ListViewFile();
}
else{
    $t = $s_ctrl->getViews(); 
}
if($t && count($t) > 0){
    sort($t);
    $table=$frm->addTable();
    $table["class"]="fitw";
    $table->setId($viewid);
    $tr=$table->addTr();
    $tr->add("th")->Content=R::ngets(IGK_FD_NAME);
    $tr->add("th", array("style"=>"width:16px"))->Content=IGK_HTML_SPACE;
    $tr->add("th", array("style"=>"width:16px"))->Content=IGK_HTML_SPACE;
    foreach($t as $k){
        if($ctrl->m_search_view && !strstr(strtolower($k), $ctrl->m_search_view))
            continue;
        $gf=substr($k, $ln);
        $sfile=((($cdir=dirname($gf)) != ".") ? $cdir."/": "").basename($gf);
        $tr=$table->addTr();
        $tr->addTd()->add("a", array("href"=>$ctrl->getUri("ca_download_view&n=".$sfile)))->Content=$sfile;
        HtmlUtils::AddImgLnk($tr->addTd(), igk_js_post_frame($ctrl->getUri("ca_edit_view&n=".$sfile)), "edit_16x16");
        if(igk_is_ajx_demand()){
            $tr->addTd()->addAJXA($ctrl->getUri("ca_drop_view&n=".$sfile))->addImg()->setSrc(R::GetImgUri("drop_16x16"))->setAttributes(["title"=>__("Drop view")]);
        }
        else{
            HtmlUtils::AddImgLnk($tr->addTd(), $ctrl->getUri("ca_drop_view&n=".$sfile), "drop_16x16");
        }
    }
}
$frm->addBtn("btn_addView", R::ngets("btn.AddView"));