<?php
// @file: tab.ctrlinfo.phtml
// @author: C.A.D. BONDJE DOUE
// @description:
// @copyright: igkdev © 2020
// @license: Microsoft MIT License. For more information read license.txt
// @company: IGKDEV
// @mail: bondje.doue@igkdev.com
// @url: https://www.igkdev.com

use function igk_resources_gets as __;

use IGK\Controllers\DefaultPageController;
use IGK\Controllers\PageControllerBase;
use IGK\Resources\R;

$this->_view_ctrl_info($s_ctrl, $dv);
 

// ($s_ctrl == null) && igk_die("selected controller not found");
// $p=$dv->div();
// $p["class"]="igk-cnf-ctrl-info";
// $p->div(array("class"=>"igk-cnf-selected-ctrl"))->
//     span_label(__("Name :"), $s_ctrl->getName());

// $p->div()->Content=R::ngets("Q.ISWEBPAGECTRL_1",  ($s_ctrl instanceof PageControllerBase))->getValue();
// $p->div()->Content=R::ngets("lb.CtrlType")->getValue(). " : ". igk_sys_ctrl_type($s_ctrl);
// $p->div()->Content=R::ngets("lb.Location_1", $s_ctrl->getDeclaredDir());
// $p->addBr();
// if(method_exists($s_ctrl, "getAppUri")){
//     $dv=$p->div();
//     $appuri=$s_ctrl->getAppUri();
//     if($appuri)
//         $dv->addABtn($appuri)->Content="Visit";
// }
// $table=$p->div()->setClass("fitw")->setStyle("overflow-x:auto")->addTable();
// $v_parent=igk_getctrl($s_ctrl->Configs->clParentCtrl, false);
// if($v_parent != null){
//     $t=$table->addTr();
//     $t->add("th")->Content=R::ngets("title.Parent");
//     $t->add("th")->Content=IGK_HTML_SPACE;
//     $tr=$table->addTr();
//     $tr->addTd()->li()->add("a", array(
//             "href"=>"#",
//             "onclick"=>"javascript:window.igk.fn.config.select_ctrl(this, '".$ctrl->TargetNode["id"]."', '".$ctrl->getUri('select_controller_ajx&n='.$s_ctrl->Configs->clParentCtrl)."'); "
//         ))->Content=$s_ctrl->Configs->clParentCtrl;
//     HtmlUtils::AddImgLnk($tr->add("td", array("style"=>"min-with:16px; min-height:16px;")), $ctrl->getUri("ca_remove_parent&clCtrl=".$s_ctrl->getName()."&clParent=".$s_ctrl->Configs->clParentCtrl), "drop_16x16");
// }
// else{
//     $tr=$table->addTr();
//     $tr->add("td", array("colspan"=>2))->Content=R::ngets("msg.noparent");
// }
// $p->addBr();
// $table=$p->div()->setClass("fitw")->setStyle("overflow-x:auto")->addTable();
// $table["class"]="fitw";
// $tr=$table->addTr();
// $tr->add("th")->Content=R::ngets("title.Childs");
// $tr->add("th")->Content=R::ngets("title.index");
// $tr->add("th", array("style"=>"width:16px"))->addSpace();
// if(igk_count($s_ctrl->Childs) > 0){
//     $tab=$s_ctrl->Childs;
//     usort($tab, "igk_sort_byNodeIndex");
//     foreach($tab as $k){
//         $tr=$table->addTr();
//         $tr->addTd()->add("a", array(
//                 "href"=>IGK_JS_VOID,
//                 "onclick"=>"javascript:window.igk.fn.config.select_ctrl(this, '".$ctrl->TargetNode["id"]."', '".$ctrl->getUri('select_controller_ajx&n='.$k->Name)."'); return false; "
//             ))->Content=$k->Name;
//         $tr->addTd()->Content=$k->TargetNode->Index;
//         HtmlUtils::AddImgLnk($tr->add("td", array("style"=>"min-with:16px; min-height:16px;")), $ctrl->getUri("ca_remove_child&clParentCtrl=".$s_ctrl->Name."&clChild=".$k->Name), "drop_16x16");
//     }
// }
// else{
//     $tr=$table->addTr();
//     $tr->add("td", array("colspan"=>3))->Content=R::ngets("msg.nochilds");
// }
// $p->addHSep();
// $table=$p->div()->setClass("fitw")->setStyle("overflow-x:auto")->addTable();
// $tr=$table->addTr();
// $tr->add("th")->Content=R::ngets("lb.properties");
// $tr->add("th")->Content=R::ngets("lb.values");
// foreach($s_ctrl->Configs as $k=>$v){
//     if($k == "clParentCtrl")
//         continue;
//     $tr=$table->addTr();
//     $tr->addTd()->addLabel()->Content=R::ngets("lb.".$k);
//     $tr->addTd()->addLabel()->Content=$v;
// }
// $div=$p->div();