<?php
// @author: C.A.D. BONDJE DOUE
// @filename: tab.infotab.phtml
// @date: 20220803 13:51:47
// @desc: 
 

use function igk_resources_gets as __; 
 

$v_dv=$t;
$dv=$v_dv->div();
$dv["class"]="controller_info";
include("tab.ctrlinfo.phtml");
$frm=$t->addForm();
$frm->addBtn("btn_remove", __("Remove"), "submit", array(
    "onclick"=>"javascript: return window.igk.ctrl.confirm_frame(this,'".__(IGK_MSG_DELETEFILE_QUESTION, $ctrl->SelectedController)."', '".
    $ctrl->getUri("drop_controller"). "');"
));