<?php
// @file: tab.ctrlinfo.phtml
// @author: C.A.D. BONDJE DOUE
// @description:
// @copyright: igkdev © 2020
// @license: Microsoft MIT License. For more information read license.txt
// @company: IGKDEV
// @mail: c.bondje.doue@igkdev.com
// @url: https://www.igkdev.com
use function igk_resources_gets as __;
use IGK\Controllers\DefaultPageController;
use IGK\Controllers\PageControllerBase;
use IGK\Resources\R;

$this->_view_ctrl_info($s_ctrl, $dv);