<?php
// @file: tab.articles.phtml
// @author: C.A.D. BONDJE DOUE
// @description:
// @copyright: igkdev © 2020
// @license: Microsoft MIT License. For more information read license.txt
// @company: IGKDEV
// @mail: bondje.doue@igkdev.com
// @url: https://www.igkdev.com

/** @var BaseController $s_ctrl */

use function igk_resources_gets as __;
use IGK\Resources\R;

($s_ctrl == null) && igk_die("selected controller not found");
$div=$t;
$v_divarticle=$div->addDiv();
$v_divarticle["id"]="view_articles";
if (!igk_is_ajx_demand())
$v_divarticle->add("h3")->Content = 
__("Article for {0}", $s_ctrl->getName());

$frm=$v_divarticle->addForm();
$frm["action"]=$ctrl->getUri("ca_add_article_frame");
$frm->addLabel()->Content= __("Lang");
$l=explode("|", igk_getctrl(IGK_CSVLANGUAGE_CTRL)->Languages);
$tab=array(IGK_ALL_LANG);
if(count($l) > 0)
    $tab=array_merge($tab, $l);
$select=igk_html_build_select($frm, "clLang", $tab, array("allowEmpty"=>false, "keysupport"=>false), $ctrl->m_selectedLang);
$ctrln=($ctrl == null) ? IGK_STR_EMPTY: "&ctrl=".$ctrl->Name;
$select["onchange"]="javascript:  (function(p){var q = p.form.parentNode; window.igk.ajx.post('".$ctrl->getUri("ca_ctrl_article_select_lang_ajx{$ctrln}&n=")."'+p.value, null, function(xhr){ if (this.isReady()){ this.setResponseTo(q); }});})(this);";
$select->setClass("igk-form-control");
include(dirname(__FILE__)."/tab.articles.list.phtml");