<?php
// @file: default.homepage.en.phtml
// @author: C.A.D. BONDJE DOUE
// @description:
// @copyright: igkdev © 2020
// @license: Microsoft MIT License. For more information read license.txt
// @company: IGKDEV
// @mail: bondje.doue@igkdev.com
// @url: https://www.igkdev.com

?>
<h1>welcome to <div class="fm-title">BALAFON
<?php
echo IGK_VERSION;
?></div></h1>

<p>
Thanks you for chosing BALAFON as your main web php framework.

You're seeing this because no project found or you didn't setup a controller as your website main controller.
</p>

<div class="mfo" >
More info ...<a href="//igkdev.com/balafon/wiki"> Read documentation</a></div>
