<?php
// @file: group.description.fr.phtml
// @author: C.A.D. BONDJE DOUE
// @description:
// @copyright: igkdev © 2020
// @license: Microsoft MIT License. For more information read license.txt
// @company: IGKDEV
// @mail: bondje.doue@igkdev.com
// @url: https://www.igkdev.com

?>
Liste des groupes. Chaque group peut être attaché à un rôle (Authorization).
<p>note: la restriction négative est d'application.</p>
