<?php
// @file: wizeinstall.welcome.fr.phtml
// @author: C.A.D. BONDJE DOUE
// @description:
// @copyright: igkdev © 2020
// @license: Microsoft MIT License. For more information read license.txt
// @company: IGKDEV
// @mail: bondje.doue@igkdev.com
// @url: https://www.igkdev.com

?>
<div style="font-size:2.8em; font-family:'Roboto', sans-serif;margin-bottom:1.2em" >
Merci d'avoir choisi BALAFON comme plateforme WEB.
</div>
<div>
Cet assistant vas vous permettre d'installer et de configurer les premiers paramètres de <b>[func: IGK_PLATEFORM_NAME ." ".IGK_VERSION]</b>.
Une fois l'installation teminer vous serez rediriger à l'interface de configuration de la plateforme.
</div>
