<?php
// @file: wizeinstall.welcome.en.phtml
// @author: C.A.D. BONDJE DOUE
// @description:
// @copyright: igkdev © 2020
// @license: Microsoft MIT License. For more information read license.txt
// @company: IGKDEV
// @mail: bondje.doue@igkdev.com
// @url: https://www.igkdev.com

?>
<div style="font-size:2.8em; font-family:'Roboto', sans-serif;margin-bottom:1.2em" >
Thank you for choosing BALAFON as your web framework.
</div>
<div>
This installation wizard will guide you through the installation process of <b>[func: IGK_PLATEFORM_NAME ." ".IGK_VERSION]</b>. When done, you will be redirect to BALAFON's configuration interface.
</div>
