<?php
// @file: abtn.fr.phtml
// @author: C.A.D. BONDJE DOUE
// @description:
// @copyright: igkdev © 2020
// @license: Microsoft MIT License. For more information read license.txt
// @company: IGKDEV
// @mail: bondje.doue@igkdev.com
// @url: https://www.igkdev.com

?>
Utilisez ce composant pour créer des liens avec l'apparence d'un bouton.
Les classes autorisées à modifier son apparence sont:
<ul>
<li>igk-danger|igk-default|igk-warning|igk-disable</li>
</ul>
<code >
//php code
$node->addABtn('link');
</code>
