<?php
// @file: ajxpickfile.fr.phtml
// @author: C.A.D. BONDJE DOUE
// @description:
// @copyright: igkdev © 2020
// @license: Microsoft MIT License. For more information read license.txt
// @company: IGKDEV
// @mail: bondje.doue@igkdev.com
// @url: https://www.igkdev.com

?>
<p>
<div class="pad-b-10" >
Crée un noeud <code class="dispib badge"> input </code> de type <b> file </b> qui permettra la capture d'un fichier en mode asynchrone.
</div>
<code class="igk-code code-php" igk-code="php">$t->addAjxPickFile($this->getAppUri($fname."/uploadfile"), "{complete:igk.ajx.fn.replace_or_append_to_body}")</code>

</p>
