<?php
// @file: balafonjs.fr.phtml
// @author: C.A.D. BONDJE DOUE
// @description:
// @copyright: igkdev © 2020
// @license: Microsoft MIT License. For more information read license.txt
// @company: IGKDEV
// @mail: bondje.doue@igkdev.com
// @url: https://www.igkdev.com

?>
Créer un nœud script propre à l'environnement de BalafonJS.
<div>
Note: les nœuds seront évalués seulement si ils sont présent au sein d'un <b>body</b>
</div>
