<?php
// @file: communitylink.fr.phtml
// @author: C.A.D. BONDJE DOUE
// @description:
// @copyright: igkdev © 2020
// @license: Microsoft MIT License. For more information read license.txt
// @company: IGKDEV
// @mail: bondje.doue@igkdev.com
// @url: https://www.igkdev.com

?>
<p>Ajouter un lien vers un r&eacute;seau social;</p>
<p><strong>exemple</strong></p>
<p>$t-&gt;addCommunityLink("googleplus", "google_uri")</p>
