<?php
// @file: component.fr.phtml
// @author: C.A.D. BONDJE DOUE
// @description:
// @copyright: igkdev © 2020
// @license: Microsoft MIT License. For more information read license.txt
// @company: IGKDEV
// @mail: bondje.doue@igkdev.com
// @url: https://www.igkdev.com

?>
Ajouter un noeud en tand que composant. Les componsants sont des noeuds qui ont une durée de vie plus longue pour l'application et qui peuvent établir
avec le système des actions à éxécuter.
Exemple:
<code>
$t->addComponent($controller, "AJXTabControl", "hpage1", 1);
</code>
