<?php
// @file: componentnodecallback.fr.phtml
// @author: C.A.D. BONDJE DOUE
// @description:
// @copyright: igkdev © 2020
// @license: Microsoft MIT License. For more information read license.txt
// @company: IGKDEV
// @mail: bondje.doue@igkdev.com
// @url: https://www.igkdev.com

?>
<igk:panel>
<div style="font-size:1.5em">Composant utiliser dans la création de composant liée. </div>
<div>
Du fait que certains componsants doivent maintenir leurs état côté serveur, il est important de pouvoir les nommés et identifier au niveau de la <b>Vue</b>.
</div>
</igk:panel>
