<?php
// @file: csslink.fr.phtml
// @author: C.A.D. BONDJE DOUE
// @description:
// @copyright: igkdev © 2020
// @license: Microsoft MIT License. For more information read license.txt
// @company: IGKDEV
// @mail: bondje.doue@igkdev.com
// @url: https://www.igkdev.com

?>
Permet d'ajouter un noeud <b>Link</b>. A utiliser avec un noeud <b>head</b>.
<div class="igk-panel">
Il prend comme paramètre le lien vers la resource (href) et un booléen qui indique si le nœud est rendu de manière temporaire ou non.
</div>
