<?php
// @file: dbselect.fr.phtml
// @author: C.A.D. BONDJE DOUE
// @description:
// @copyright: igkdev © 2020
// @license: Microsoft MIT License. For more information read license.txt
// @company: IGKDEV
// @mail: bondje.doue@igkdev.com
// @url: https://www.igkdev.com

?>
<p>Permet la cr&eacute;ation d'un noeud "select" avec comme source de donn&eacute;e un r&eacute;sultat provenant du syst&egrave;me de selection.</p>
<p>QueryResult</p>
