<?php
// @file: fixedactionbar.fr.phtml
// @author: C.A.D. BONDJE DOUE
// @description:
// @copyright: igkdev © 2020
// @license: Microsoft MIT License. For more information read license.txt
// @company: IGKDEV
// @mail: bondje.doue@igkdev.com
// @url: https://www.igkdev.com

?>
Représente une barre d 'action vertical fixée. Celle-ci sera uniquement visible
lors du scroll d'un élément cible.

<igk:code class="dispb" style="margin: 2em 0em; display:block;">$this->addFixedActionBar("controller", 200);</igk:code>
