<?php
// @file: frame.fr.phtml
// @author: C.A.D. BONDJE DOUE
// @description:
// @copyright: igkdev © 2020
// @license: Microsoft MIT License. For more information read license.txt
// @company: IGKDEV
// @mail: bondje.doue@igkdev.com
// @url: https://www.igkdev.com

?>
Les "frames" sont des conteneurs qui pourront être superposés et navigables. Ils sont marqué de la classe <b>frame</b> et <b>igk-ui-frame</b>.
