<?php
// @file: jsserviceworker.fr.phtml
// @author: C.A.D. BONDJE DOUE
// @description:
// @copyright: igkdev © 2020
// @license: Microsoft MIT License. For more information read license.txt
// @company: IGKDEV
// @mail: bondje.doue@igkdev.com
// @url: https://www.igkdev.com

?>
<p>Il s'agit ici d'un composant utilitaire. permettant d'ajouter un <strong>Service Worker</strong> script dans une Vue.</p>
