<?php
// @file: moreview.fr.phtml
// @author: C.A.D. BONDJE DOUE
// @description:
// @copyright: igkdev © 2020
// @license: Microsoft MIT License. For more information read license.txt
// @company: IGKDEV
// @mail: bondje.doue@igkdev.com
// @url: https://www.igkdev.com

?>
Tous les noeuds qui suivent ce dernier seront cachés. Lorsqu'il est actif il est <code class="badge dispib">...</code> par defaut.
