<?php
// @file: notifyhostbind.fr.phtml
// @author: C.A.D. BONDJE DOUE
// @description:
// @copyright: igkdev © 2020
// @license: Microsoft MIT License. For more information read license.txt
// @company: IGKDEV
// @mail: c.bondje.doue@igkdev.com
// @url: https://www.igkdev.com

?>
<p>Repr&eacute;sente un noeud web appliqu&eacute; du style <strong>igk-notify-host-bind</strong> qui permet d'afficher une zone&nbsp; message de notification.</p>