<?php
// @file: repeatcontent.fr.phtml
// @author: C.A.D. BONDJE DOUE
// @description:
// @copyright: igkdev © 2020
// @license: Microsoft MIT License. For more information read license.txt
// @company: IGKDEV
// @mail: bondje.doue@igkdev.com
// @url: https://www.igkdev.com

?>
<p>Composant permettant de rep&eacute;ter son contenu. le param&egrave;tre <strong>igk-repeat</strong> indique &agrave; BalafonJS de dupliquer et d'initialiser son contenu.</p>
