<?php
// @file: rollin.fr.phtml
// @author: C.A.D. BONDJE DOUE
// @description:
// @copyright: igkdev © 2020
// @license: Microsoft MIT License. For more information read license.txt
// @company: IGKDEV
// @mail: bondje.doue@igkdev.com
// @url: https://www.igkdev.com

?>
<div style="text-indent: 2em; padding-bottom:1.2em;">
Element qui sera affiché au moment du survol de la souris sur le parent. Le parent doit être marquer de la classe css <b>igk-roll-owner</b> pour
enclenché le mécanisme.
</div>

<div style="text-indent: 2em; padding-bottom:1.2em;" >Par défaut l'affichage de l'élément se fera de la gauche. Pour modifier ce compotement ajouté une class de direction comme <b>igk-pull-right</b>
pour que ce mécanisme d'affichage debute par la droite.
</div>
<div>
<code igk-code="php" >
$t->addDiv()->setClass("igk-roll-owner")->addRollIn()->addDiv()->Content = "...";
</code>
</div>
