<?php
// @file: symbol.fr.phtml
// @author: C.A.D. BONDJE DOUE
// @description:
// @copyright: igkdev © 2020
// @license: Microsoft MIT License. For more information read license.txt
// @company: IGKDEV
// @mail: bondje.doue@igkdev.com
// @url: https://www.igkdev.com

?>
Utiliser pour afficher une <a href="#" alt="symbolic symbol">image symbolique </a>préalable chargé du côté client.
<p>
Vous pouvez ajouter un fichier de symbole à la plateforme et ainsi utiliser le code d'enregistrement pour afficher le dit symbole.
</p>
