<?php
// @file: togglestatebutton.fr.phtml
// @author: C.A.D. BONDJE DOUE
// @description:
// @copyright: igkdev © 2020
// @license: Microsoft MIT License. For more information read license.txt
// @company: IGKDEV
// @mail: bondje.doue@igkdev.com
// @url: https://www.igkdev.com

?>
Permet de placer dans un document un <b>checkbox</b> avec l'aspect d'un bouton à état. Le style du checkbox est donné de manière dynamique à l'aide du parametre <b><i>style</i></b>
