<?php
// @file: topnavbar.fr.phtml
// @author: C.A.D. BONDJE DOUE
// @description:
// @copyright: igkdev © 2020
// @license: Microsoft MIT License. For more information read license.txt
// @company: IGKDEV
// @mail: bondje.doue@igkdev.com
// @url: https://www.igkdev.com

?>
<p>Element utilisé pour attaché du contenu à l'en tête du document. Crée un <strong>div</strong>		 qui sera marqué de l'attribute <em class="igk-jsa">igk-top-nav-bar</em>		 à 1.</p>
<p>D'autres attribute html entre en jeux</p>
<table><tbody><tr><th>Nom</th><th>Description</th></tr><tr><td>igk-nav-bar-options</td><td><p> expression json qui définie les options de la barre de navigation.</p><p>{offset}</p></td></tr><tr><td>igk-nav-bar-target</td><td><p> expression de recherche de la cible de noeud de reference. par défault il sagit </p><p>du parent marquer de la class .igk-parentscroll. donc l'expression est ^.igk-parentscroll</p></td></tr></tbody></table>
