<?php
// @file: trackbarnode.fr.phtml
// @author: C.A.D. BONDJE DOUE
// @description:
// @copyright: igkdev © 2020
// @license: Microsoft MIT License. For more information read license.txt
// @company: IGKDEV
// @mail: bondje.doue@igkdev.com
// @url: https://www.igkdev.com

?>
<div>
Créer un noeud qui represente une rangé de données. Sa présentation est géré par le navigateur.
</div>

<igk:trackbarnode igk:args="demo, 127, 0, 255"/>
