<?php
// @file: webglgamesurface.fr.phtml
// @author: C.A.D. BONDJE DOUE
// @description:
// @copyright: igkdev © 2020
// @license: Microsoft MIT License. For more information read license.txt
// @company: IGKDEV
// @mail: bondje.doue@igkdev.com
// @url: https://www.igkdev.com

?>
Permet de créer une surface de dessin prête pour rendre du contenue 3D webgl grace au noeud canvas html5.
<p>
Le module <b>"bge"</b> est requis avant de pouvoir utiliser ce composant.
</p>
