<?php
// @file: xslt.fr.phtml
// @author: C.A.D. BONDJE DOUE
// @description:
// @copyright: igkdev © 2020
// @license: Microsoft MIT License. For more information read license.txt
// @company: IGKDEV
// @mail: bondje.doue@igkdev.com
// @url: https://www.igkdev.com

?>
<p>Permet la tranformation a chaud d'un contenu xml &agrave; l'aide de xslt c&ocirc;t&eacute; client.</p>
<p>Pour une une transformation c&ocirc;t&eacute; serveur faite appel &agrave; la fonction utilitaire&nbsp;<strong>igk_xslt_transform</strong>.</p>
