<?php
// @file: 404.phtml
// @author: C.A.D. BONDJE DOUE
// @description:
// @copyright: igkdev © 2020
// @license: Microsoft MIT License. For more information read license.txt
// @company: IGKDEV
// @mail: bondje.doue@igkdev.com
// @url: https://www.igkdev.com

/** @var string $headers */
/** @var string $title */
/** @var string $msg */
/** @var string $txtoptions */
/** @var string $trace_data */

?>
<!DOCTYPE html>
<!-- page: balafoncore 404 error: -->
<html>
<head>
<title><?= $title ?></title>
<?= $headers ?>
</head>
<body>
<div class="core-error" >
<?= $msg ?>
</div>
<div class="error-page">
<div class="igk-container">
<div class="pic" style="color:#999; margin-left:-10px; margin-right:-10px; margin-bottom:-10px">
<?= $txtoptions ?>
<?= $trace_data ?>
<?php
igk_dev_wln($_SERVER);
?></div>
</div>
</div>
</body>
</html>
