<?php
// @file: homebutton.fr.phtml
// @author: C.A.D. BONDJE DOUE
// @description:
// @copyright: igkdev © 2020
// @license: Microsoft MIT License. For more information read license.txt
// @company: IGKDEV
// @mail: bondje.doue@igkdev.com
// @url: https://www.igkdev.com

?>
<p>
Ajoute a la page un bouton de navigation qui vous dirige vers l'accueil.
</p>
<div class="igk-remark">
<ul>
<li>Pour le scroll le bouton recherche dans la chaine du parent l'élément marquer de la class <span class="igk-css-cl" >.igk-parentscroll</span></li>
<li>Un élément ayant l'id <span class="igk-css-id">"home"</span> doit être présent sur la page</li>
</ul>
</div>
