<?php
// @file: roll.fr.phtml
// @author: C.A.D. BONDJE DOUE
// @description:
// @copyright: igkdev © 2020
// @license: Microsoft MIT License. For more information read license.txt
// @company: IGKDEV
// @mail: bondje.doue@igkdev.com
// @url: https://www.igkdev.com

?>
<div>
<igk:panel>
Utilisation :
<ul>
<li>le parent du noeud doit posséder la class igk-roll-owner pour un mecanism au passage de la souris</li>
<li>ou</li>
<li>le parent du noeud doit posséder la class igk-touch-roll-owner</li>
</igk:panel>

l'orientation se fait en application classe de pousser.

<div class="fitw">
<table class="igk-table" width="100%">
<tr><td>igk-pull-right</td></tr>
<tr><td>igk-pull-bottom</td></tr>
<tr><td>igk-pull-top</td></tr>
</table>
</div>
par défaut le noeud est placer à gauche

</div>
<code igk_language="php">
$n = new IGKHtmlItem("div");
$n->setClass("igk-roll-owner");
$roll = $n->addRoll();

/*insert roll to pdata */

</code>
