<?php
// @file: tabcontrolnodeajx.fr.phtml
// @author: C.A.D. BONDJE DOUE
// @description:
// @copyright: igkdev © 2020
// @license: Microsoft MIT License. For more information read license.txt
// @company: IGKDEV
// @mail: bondje.doue@igkdev.com
// @url: https://www.igkdev.com

?>
Permet d'ajouter un control de page.

<p>
Ajouter des pages :
</p>
<div>
<code lang="igk-html">
addTabPage(title, uri, [active=false]);
</code>
</div>
